In [ ]:
# Numpy: Numerical Python- Linear Algebra Library for Python
# Numpy is incredibly fast as it has bindings to C libraries
# pip install numpy
# ndarray(N-dimentional array) : Collection of items of the same type which are accessed using zero based index

In [34]:
# Convert list to a 1D array
import numpy as np
my_list = [10,20,30]
arr = np.array(my_list)
print(type(arr)) # The output of 1D array: [10,20,30]
print(arr.shape) # The shape of 1D array(either row or column) : (3,)
print(arr.dtype) # The data type within an array :int64

<class 'numpy.ndarray'>
(3,)
int64


In [35]:
# Convert list of list into 2D array 
my_list = [[1,2,3],[4,5,6],[7,8,9]]
arr_2D = np.array(my_list)
print(arr_2D)
print(arr_2D.shape)
print(arr_2D.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64


In [36]:
# Reshape a list into an array 

my_list = list(range(1,26))
print(len(my_list))
arr = np.array(my_list)
print(arr.shape)

arr_reshape = arr.reshape(5,5)
print(arr_reshape)
print(arr_reshape.shape)


25
(25,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [26]:
# arange : similar to range in Python 
print(np.arange(0,10,3))

# zeros : Define the number of rows and columns as tuples
print(np.zeros(2)) # array([0.,0.])
print(np.zeros((2,3)))

#ones
print(np.ones(3)) # array([1.,1.,1.])
print(np.ones((2,3)))

# eye :identity matrix
print(np.eye(4)) # generates a 4x4 matrix with diagonal as 1 

# linspace : Creates 7 evenly distributed numbers between 0 and 10
print(np.linspace(0,10,7))

# random.rand : Generate randon numbers which are uniformly distributed
print(np.random.rand(3,4))

# random.randn : Generate randon numbers which are normally distributed
print(np.random.randn(3,4))

# random.randint : Generate 'X' random numbers between a and b 
# 10 random numbers between 0 and 20 
print(np.random.randint(0,20,10)) 

arr = np.random.randint(0,50,10)

arr.max() # Maximum value in the list 
arr.argmax() # The index position for the maximum value

arr.min() # Minimum value in the list 
arr.argmin() # The index position for the minimum value

[0 3 6 9]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
[[0.9948995  0.72160361 0.22955686 0.25446214]
 [0.52387185 0.19540724 0.95633531 0.99473097]
 [0.59159165 0.21438182 0.95330358 0.10192611]]
[[-1.63851498 -1.15284642 -0.76890277 -1.49512565]
 [ 0.34882989 -0.47184052 -0.24561509  1.00280347]
 [ 0.39157397  1.32935218 -0.65622512  0.72055588]]
[15 13 12 12 10 17  1 14  6  4]


In [14]:
# Indexing and Selection 
import numpy as np
arr = np.arange(0,11)
print(arr)

# 1D indexing and slicing 
arr[8] # 8 
arr[1:5] # 1,2,3,4


[ 0  1  2  3  4  5  6  7  8  9 10]


array([1, 2, 3, 4])

In [29]:
# 2D indexing and slicing
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr_2d)
print(arr_2d[0]) # 1st row values
print(arr_2d[:,1]) # 2nd column values
print(arr_2d[1:,2]) # Out of last 2 rows given me column 2 values

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[ 5 10 15]
[10 25 40]
[30 45]


In [37]:
# Fancy Indexing 
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]

for i in range(arr_length):
    arr2d[i] = i 

print(arr2d)
print(arr2d[[2,4,6,8]])
print(arr2d[[6,4,3,1]]) # indexing in any order

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]
[[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
# Broadcasting
arr
slice_of_arr = arr[0:6]
slice_of_arr

# Do operation on the slice 
slice_of_arr[:] = 99
slice_of_arr

# The changes we do on the slice is getting copied over to the main array. 
# This is done to avoid memory problems
arr 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Operations 
arr = np.arange(0,10)

print(arr)

arr + arr  # addition 

arr - arr # Subtraction

arr * arr # Multiplication 

arr / arr # Division ( warning division by zero, replaced with nan)

1/ arr  # 0/1 is infinity warning not an error, replaced with inf

arr * 3 

# Universal Array Functions 
np.sqrt(arr) # Square root of an array 

np.exp(arr) # Exponencial of an array (e^)

np.max(arr) # Maximum value in an array 

np.sin(arr) # sine value of an array 

np.log(arr) # log value of an array 