In [ ]:
#Pandas : Pannel Data
# Every column in a pandas dataframe is a series 

# Series: 1D labelled array
# Data frame: 2D labelled array
# Panel : 3D labelled array
# Pannel 4D: 4D labelled array 

# What is the difference between numpy array and series? 
# Series have labelled index
# It doesn't need to hold numeric data, it cab hold any arbitary Python Object 

In [2]:
# Series 
# Creating series from lists
import pandas as pd

my_list = [10,20,30]
series = pd.Series(my_list)
print(series)
print(series.index) # series index 
print(series.values) # series values : output is an array


0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]


In [3]:
# Creating series from numpy array 
import numpy as np
import pandas as pd
arr = np.arange(0,5)

# To create labelled index just add list of index values as an argument
series = pd.Series(arr,index = ['a','b','c','d','e'])

print(series)
print(series.index) # series index 
print(series.values) # series values

a    0
b    1
c    2
d    3
e    4
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[0 1 2 3 4]


In [10]:
# Creating series from dictionary 
my_dict = {'a':10,'b':20,'c':30}
series = pd.Series(my_dict)

print(series)
print(series.index) # series index 
print(series.values) # series values

a    10
b    20
c    30
dtype: int64
Index(['a', 'b', 'c'], dtype='object')
[10 20 30]


In [6]:
# Using a index 
ser1 = pd.Series([1,2,3,4],index = ['USA','Germany','USSR','Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA','Germany','Italy','Japan'])
print(ser1['USA'])
print(ser1 +ser2)

1
Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64


In [7]:
# Pandas 
import pandas as pd
import numpy as np

In [21]:
from numpy.random import randn
np.random.seed(101) # This will make sure output doesn't change 
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(),columns = 'W X Y Z'.split())
print(df)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [26]:
# Some Operations 
print(df['W']) # Extract values for column W 
print(df[['W','X']]) # Extract values of column W and X 
type(df['W']) # Find data type of column W : Series 
df['new'] = df['W'] + df['Y'] # Creating a new column from exsisting columns

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64
          W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757


W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
# axis = 1 indicates drop column , axis = 0 indicates drop row
# inplace = True makes sure that changes are applied to the main dataframe rather 
# just the output
df.drop("new",axis = 1,inplace = True) 
df.drop("E",axis = 0) 

In [43]:
# Selecting rows 
print(df)
print(df.loc["A"]) # loc : based off label 
print(df.iloc[2]) # iloc : based off position

print(df.loc['B','Y']) # Selecting row B and C 
print(df.loc[['A','B'],['W','Y']])

In [46]:
# Conditional Selection 
print(df)

# Print data frame values with values in column W greater than zero and the putput should 
# display columns Y and X 
df[df['W']>0][['Y','X']]

# Print data frame values with values in column W greater than zero and values 
# in column Y greater than 1 

# & indicates 'and' operation 
# | indicates 'or' operation
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762


Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [ ]:
# Set and Reset index values 

In [47]:
print(df)

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762


In [53]:
# reset dataframe operations 
# a new column called index is created with prior index values 
# The new index values are set starting from 0 
df.reset_index(inplace = True)

# Remove the index columns 
df.drop('index',axis = 1 , inplace = true)

# Create a new index 
df['states'] = 'CA NY WY OR CO'.split()

# Set states column as new index 
df.set_index('states',inplace = True)

print(df)

In [89]:
# Multi Index and Index Hierarchy 

outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

print(hier_index)

import numpy as np
df = pd.DataFrame(np.random.randn(6,2),index = hier_index,columns=['A','B'])
print(df)
print(df.loc['G1'])
print(df.loc['G1'].loc[1])

print(df.index.names) # Check if multi index columns have names associated with it 
df.index.names = ['Group','Num']
df

print(df.xs(['G1',1]))

print(df.xs(1,level = 'Num'))

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )
             A         B
G1 1 -0.380104 -1.666059
   2 -2.736995  1.522562
   3  0.178009 -0.626805
G2 1 -0.391089  1.743477
   2  1.130018  0.897796
   3  0.330866 -1.063049
          A         B
1 -0.380104 -1.666059
2 -2.736995  1.522562
3  0.178009 -0.626805
A   -0.380104
B   -1.666059
Name: 1, dtype: float64
[None, None]
A   -0.380104
B   -1.666059
Name: (G1, 1), dtype: float64
              A         B
Group                    
G1    -0.380104 -1.666059
G2    -0.391089  1.743477


/var/folders/1j/wrwgh3d572b7qrc_0mgsxj6w0000gn/T/ipykernel_61488/1699116021.py:20: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  print(df.xs(['G1',1]))


In [94]:
# Working with missing data 
import pandas as pd 
import numpy as np

df = pd.DataFrame({'A':[1,2,np.nan],
                   'B':[5,np.nan,np.nan],
                   'C':[1,2,3]})

# How to drop nan values using pandas ?
# This drops all rows with nan values
# By default axis = 0
df.dropna()

# Drop columns which have null values
df.dropna(axis = 1)

# Thresh(Threshold) sets the number of nan values in a row before filtering/dropping 
df.dropna(thresh = 2)

# How to fill na values in a pandas data frame?
print(df.fillna(value = 'Fill value'))

# Fill the missing values in column A with the mean value in column A 
print(df['A'].fillna(value = df['A'].mean()))

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [106]:
# Group By 

data = pd.DataFrame({'Company':['Goog','Goog','Msft','Msft','Fb','Fb'],
        'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sales':[200,120,340,124,243,350]})

# data.groupby(<name_of_the_column>) creates a DataFrameGroupBy object

by_comp = data.groupby('Company')

by_comp.mean()
by_comp.max()
by_comp.std()
by_comp.min()
by_comp.count()
by_comp.describe()
by_comp.describe().transpose()['Goog']

Company   Person  Sales
0    Goog      Sam    200
1    Goog  Charlie    120
2    Msft      Amy    340
3    Msft  Vanessa    124
4      Fb     Carl    243
5      Fb    Sarah    350

In [129]:
# Concatenation glues data frame together(Union)
# Dimensions should match along the axis we are concatenating on
# All the column names are the same but,the index values are different 
# By default concat considers axis = 0

# Use case: Lets say we have 10 files with same columns but we need to combine them 
# for analysis 


df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

print(pd.concat([df1,df2,df3]))
print(pd.concat([df1,df2,df3],axis =1))

# Merging : Similar to SQL 
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})  

pd.merge(left,right,how = 'inner',on ='key')


left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

pd.merge(left, right, on=['key1', 'key2'])
pd.merge(left, right, how='outer', on=['key1', 'key2'])
pd.merge(left, right, how='right', on=['key1', 'key2'])
pd.merge(left, right, how='left', on=['key1', 'key2'])


# Joining :Convenient method of combining the columns of 2 potentially 
# differently -indexed data frames into a single result data frame 

left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

left.join(right)
left.join(right,how = 'outer')

# What is the difference between merge and join?

# Both are can be used to combine dataframe but 
# join uses index to combine 2 dataframe
# merge allows us to choose the column(s) to join dataframe

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN 

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [140]:
# Practice Operations
# unique : prints unique values in a column of a dataframe(Included N/A or null values)
# nunique : returns the number(count) of unique values This is similar to finding length + unique function 
# nunique excludes N/A or null values before calculation
# value_counts() : returns column values and number of times they have appeared in the dataset
# value_counts() excludes N/A or null values before calculation

df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

df['col2'].unique() # prints all unique values in column col2
df['col2'].nunique() # prints the number of unique values 
df['col2'].value_counts() # prints count of how many times values in column is repeated

# Apply method 

def times2(x):
    return x*2

df['col1'].apply(times2)
df['col3'].apply(len)
df['col1'].sum() # Series have a method called sum() to add elements

# Permanently remove columns
del df['col1']

df.columns # Get all columns names for a dataframe
df.index # Get index values for a dataframe

# Sorting 
df.sort_values(by='col2',inplace = True)

df.isnull() # Check for Null Values 
df.dropna() # Drop rows with nan Values

# Pivot Table 
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)
df.pivot_table(values = 'D',index=['A','B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [143]:
# Data input and output

# Reading data from a CSV file
df = pd.read_csv('example.csv')

# Writing data to a csv file
df.to_csv('example',index=False)

# Reading data from a excel file
pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

# Writing data to a excel file
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')


# Reading a HTML file 
# We may need to install beautiful soup4, lxml, html5lib

df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')
df[0] # Extracts first table in the HTML file